Repository hybridapp-io/ham-deploy, pull requests merged in 2020-07, with the labels that each got.

#16 change crd installation from v1beta1 to dynamic interface
  pkg/controller/operator/container_generator.go
  pkg/controller/operator/operator_controller.go
  pkg/utils/kubernetes.go
Labels: approved, lgtm, size/M

#17 update reconcile
  pkg/controller/operator/operator_controller.go
  pkg/controller/operator/operator_controller_test.go
Labels: approved, lgtm, size/M

#18 Add replicas option; Add Labels to generated resources
  deploy/crds/deploy.hybridapp.io_operators_crd.yaml
  deploy/crds/deploy.hybridapp.io_v1alpha1_operators_cr.yaml
  deploy/operator.yaml
  pkg/apis/deploy/v1alpha1/operator_types.go
  pkg/apis/deploy/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operator/container_generator.go
  pkg/controller/operator/operator_controller.go
  pkg/controller/operator/operator_controller_test.go
Labels: approved, lgtm, size/XXL

#20 updated owners list
  OWNERS
Labels: approved, lgtm, size/XS
