Repository hybridapp-io/ham-deploy, pull requests merged in 2020-05, with the labels that each got.

#2 initial unit testing
  README.md
  cmd/operator/operator.go
  examples/simple-cr.yaml
  go.mod
  pkg/controller/deployment/deployment_controller_test.go
  pkg/controller/deployment/deployment_suite_test.go
  pkg/utils/kubernetes.go
Labels: approved, lgtm, size/L

#3 fix image build.
  .gitignore
  build/bin/entrypoint
  build/bin/user_setup
Labels: approved, lgtm, size/S

#4 fix badge links in readme
  README.md
  build/bin/entrypoint
Labels: approved, lgtm, size/S

#5 Hubconn
  deploy/crds/tools.hybridapp.io_deployments_crd.yaml
  deploy/operator.yaml
  pkg/apis/tools/v1alpha1/deployment_types.go
  pkg/apis/tools/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/deployment/container_generator.go
  pkg/controller/deployment/deployment_controller.go
  pkg/controller/deployment/deployment_controller_test.go
Labels: approved, lgtm, size/XL

#6 rename kind to satisfy operator testing
  deploy/crds/tools.hybridapp.io_operators_crd.yaml
  deploy/role.yaml
  examples/simple-cr.yaml
  pkg/apis/tools/v1alpha1/operator_types.go
  pkg/apis/tools/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_operator.go
  pkg/controller/operator/container_generator.go
  pkg/controller/operator/operator_controller.go
  pkg/controller/operator/operator_controller_test.go
  pkg/controller/operator/operator_suite_test.go
Labels: approved, lgtm, size/L

#8 fix the issue of comparing volumes of pods
  pkg/controller/operator/operator_controller.go
Labels: approved, lgtm, size/XS

#9 fix typo in path
  OWNERS
  pkg/controller/operator/operator_controller.go
Labels: approved, lgtm, size/XS

#10 fix issue in loading config from pod
  build/Dockerfile
  cmd/operator/operator.go
  deploy/crds/tools/assembler/tools.hybridapp.io_applicationassemblers_crd.yaml
  pkg/controller/operator/operator_controller.go
Labels: approved, lgtm, size/L
